// Model → TypeScript `.d.ts` bytes — TypeScript port of
// `src/SchemaExport/TsTypes.zig`.
//
// Emits one interface per form (`<Plugin>_<Form>` PascalCase), one
// type alias per value-kind, a `Sjon<Plugin>` barrel union per
// plugin. The output describes the canonical JSON shape of
// `sjon to-json` — `$form`, `$ns`, `$kw`, `$sym`, etc.
//
// Structural parity with Zig:
//
//   * Same brand definitions (`Keyword<>`, `Symbol_<>`, `SjonDate`,
//     `SjonTime`, `SjonExpr<>`, `CrossRef<>`)
//   * Same form-naming scheme: `<Plugin>_<Form>` PascalCase
//   * Same per-key/per-shape mapping: optional `?`, literal `$form`,
//     branded `Symbol_<>` for members, tuple `[number, "deg"]` for
//     unit-bearing numbers, JSDoc `@minimum`/`@maximum`/`@minLength`/
//     `@maxLength`/`@pattern`/`@format`/`@sjon-cross-ref` annotations
//
// Discriminated forms and exclusive groups are emitted here too, now that
// `loader.ts` parses them: a discriminated form becomes a per-variant union
// (`writeDiscriminatedFormType`) and every group adds a
// `@sjon-exclusive-group` JSDoc line. On the `kit` / `kit-xor` fixtures the
// output is byte-identical to the Zig goldens except for the JSDoc a
// `:description` produces — the one manifest field this port's loader still
// does not read. `test/schemaExport.test.ts` asserts exactly that.

import type {
  Model,
  ModelCrossRef,
  ModelDiscriminator,
  ModelForm,
  ModelKey,
  ModelMember,
  ModelNumericBounds,
  ModelPlugin,
  ModelStringBounds,
  ModelUnitShape,
  ModelValueShape,
} from './model.ts';
import { isBoundedRef } from './model.ts';
import type { Warning } from './warnings.ts';
import type { Repr } from '../plugin.ts';
import { assertNever } from '../internal.ts';

// Branded TS alias for a GPU representation tag. The aliases are defined
// in BRAND_PRELUDE; this maps the `Repr` union to the alias name so a
// `:repr`-tagged number renders as `F32` … `F16` instead of `number`.
// Exhaustive switch (no default): a new `Repr` is a noImplicitReturns error.
function reprTsAlias(repr: Repr): string {
  switch (repr) {
    case 'f32':
      return 'F32';
    case 'u32':
      return 'U32';
    case 'i32':
      return 'I32';
    case 'u16':
      return 'U16';
    case 'f16':
      return 'F16';
  }
}

const BRAND_PRELUDE = `
export type Keyword<S extends string = string> = { readonly $kw: S };
export type Symbol_<S extends string = string> = { readonly $sym: S };
export type SjonDate = { readonly $date: string };
export type SjonTime = { readonly $time: string };
export type SjonExpr<TResult = unknown> = { readonly $expr: unknown[] } & { readonly __sjonResult?: TResult };
export type CrossRef<TargetForm extends string = string, S extends string = string> = Symbol_<S> & { readonly __sjonRef?: TargetForm };
export type F32 = number & { readonly __sjonRepr?: "f32" };
export type U32 = number & { readonly __sjonRepr?: "u32" };
export type I32 = number & { readonly __sjonRepr?: "i32" };
export type U16 = number & { readonly __sjonRepr?: "u16" };
export type F16 = number & { readonly __sjonRepr?: "f16" };
`;

interface EmitContext {
  readonly filterPlugin: string | null;
  readonly model: Model;
}

export function emit(model: Model, warnings: readonly Warning[]): string {
  return emitWithContext(model, warnings, { filterPlugin: null, model });
}

export function emitForPlugin(
  model: Model,
  plugin: ModelPlugin,
  warnings: readonly Warning[],
): string {
  return emitWithContext(model, warnings, { filterPlugin: plugin.name, model });
}

function emitWithContext(model: Model, warnings: readonly Warning[], ctx: EmitContext): string {
  let out = '';
  out += writeHeader(model.version, warnings);
  out += BRAND_PRELUDE + '\n';
  if (ctx.filterPlugin) {
    out += writeCrossPluginImports(model, ctx.filterPlugin);
  }
  for (const p of model.plugins) {
    if (ctx.filterPlugin && p.name !== ctx.filterPlugin) continue;
    out += `\n// ----- plugin: ${p.name} -----\n\n`;
    for (const f of p.forms) {
      out += writeForm(p, f, ctx);
    }
    out += writeBarrel(p);
  }
  return out;
}

function writeHeader(version: number, warnings: readonly Warning[]): string {
  let out = `// sjon-export-version: ${version}\n`;
  out += '// Generated by sjon — do not edit by hand.\n';
  out += '// Describes the canonical JSON shape of `sjon to-json`.\n';
  if (warnings.length > 0) {
    out += '//\n// Export warnings:\n';
    for (const w of warnings) {
      out += `//   [${w.severity} ${w.code}] ${w.message}\n`;
    }
  }
  return out;
}

function writeCrossPluginImports(model: Model, thisPlugin: string): string {
  const seen = new Map<string, Set<string>>();
  for (const p of model.plugins) {
    if (p.name !== thisPlugin) continue;
    for (const f of p.forms) {
      collectCrossPluginRefsFromForm(f, thisPlugin, seen);
    }
  }
  if (seen.size === 0) return '';
  let out = '';
  for (const [otherPlugin, names] of seen) {
    const sortedNames = [...names].sort();
    const idents = sortedNames.map((n) => formTypeName(otherPlugin, n)).join(', ');
    out += `import type { ${idents} } from "./${otherPlugin}";\n`;
  }
  return out + '\n';
}

function collectCrossPluginRefsFromForm(
  form: ModelForm,
  thisPlugin: string,
  seen: Map<string, Set<string>>,
): void {
  for (const k of form.keys) {
    collectCrossPluginRefsFromShape(k.value, thisPlugin, seen);
  }
  // Variant keys emit into the same file and so need the same imports.
  for (const v of form.discriminator?.variants ?? []) {
    for (const k of v.keys) collectCrossPluginRefsFromShape(k.value, thisPlugin, seen);
  }
  if (form.positional.kind === 'kind') {
    collectCrossPluginRefsFromShape(form.positional.shape, thisPlugin, seen);
  }
}

function collectCrossPluginRefsFromShape(
  shape: ModelValueShape,
  thisPlugin: string,
  seen: Map<string, Set<string>>,
): void {
  switch (shape.kind) {
    case 'form_heads':
      for (const head of shape.heads) {
        if (!head.plugin || head.plugin === thisPlugin) continue;
        if (!seen.has(head.plugin)) seen.set(head.plugin, new Set());
        seen.get(head.plugin)!.add(head.name);
      }
      break;
    case 'vector':
      collectCrossPluginRefsFromShape(shape.vector.element, thisPlugin, seen);
      break;
    case 'union_of':
      for (const alt of shape.alternatives) {
        collectCrossPluginRefsFromShape(alt.shape, thisPlugin, seen);
      }
      break;
    default:
      break;
  }
}

function writeForm(plugin: ModelPlugin, form: ModelForm, ctx: EmitContext): string {
  const doc = writeFormDoc(form);
  return form.discriminator
    ? doc + writeDiscriminatedFormType(plugin, form, form.discriminator, ctx)
    : doc + writeFormInterface(plugin, form, ctx);
}

function writeFormInterface(plugin: ModelPlugin, form: ModelForm, ctx: EmitContext): string {
  let out = `export interface ${formTypeName(plugin.name, form.name)} {\n`;
  out += `  $form: "${form.name}";\n`;
  out += `  $ns: "${plugin.name}";\n`;
  // Sort keys alphabetically (mirrors Zig's sortKeysAlphabetically).
  for (const k of sortKeys(form.keys)) {
    out += writeKey(k, '  ', ctx);
  }
  out += writeChildren(form, '  ', ctx);
  if (form.open) {
    out += '  [key: string]: unknown;\n';
  }
  out += '}\n\n';
  return out;
}

/**
 * A discriminated form is a `type` union, one branch per variant, not an
 * `interface`: the discriminant is branded to the variant's `:when`, so TS
 * narrows the branch — and with it the variant-only keys — from the value of
 * one property. An interface with every variant key optional would type-check
 * a document mixing two variants, which is the thing the discriminant exists
 * to forbid. Mirrors `writeDiscriminatedFormType` in
 * `src/SchemaExport/TsTypes.zig`.
 */
function writeDiscriminatedFormType(
  plugin: ModelPlugin,
  form: ModelForm,
  disc: ModelDiscriminator,
  ctx: EmitContext,
): string {
  let out = `export type ${formTypeName(plugin.name, form.name)} =`;
  for (const v of disc.variants) {
    out += '\n  | {\n';
    out += `      $form: "${form.name}";\n`;
    out += `      $ns: "${plugin.name}";\n`;
    for (const k of sortKeys(form.keys)) {
      out +=
        k.name === disc.keyName
          ? writeDiscriminantKey(k, v.when, '      ')
          : writeKey(k, '      ', ctx);
    }
    for (const vk of sortKeys(v.keys)) {
      out += writeKey(vk, '      ', ctx);
    }
    out += writeChildren(form, '      ', ctx);
    if (form.open) out += '      [key: string]: unknown;\n';
    out += '    }';
  }
  return `${out};\n\n`;
}

function sortKeys(keys: readonly ModelKey[]): ModelKey[] {
  return [...keys].sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * TypeScript cannot express "exactly one element of this union in an
 * array", so a bounded head-set's counts ride as a doc comment above the
 * `$children` member and nothing more. Documented as a known weakening in
 * `docs/SCHEMA_EXPORT.md`: a silently weaker `.d.ts` is worse than a
 * documented one. Returns the empty string when nothing is bounded.
 *
 * The inline local-form literal is deliberately not given one — that
 * surface carries no JSDoc at all, by design. Mirrors Zig's
 * `writeChildCountsDoc`.
 */
function childCountsDoc(shape: ModelValueShape, indent: string): string {
  if (shape.kind !== 'form_heads') return '';
  const bounded = shape.heads.filter(isBoundedRef);
  if (bounded.length === 0) return '';
  const parts = bounded.map((h) => {
    const min = h.min ?? 0;
    if (h.max === undefined) return `${h.name}: ${min}..`;
    return h.max === min ? `${h.name}: ${h.max}` : `${h.name}: ${min}..${h.max}`;
  });
  return `${indent}/** Positional counts (not expressible in TS): ${parts.join('; ')} */\n`;
}

/** The `$children` line for a form's positional slot, shared by the interface
 *  and per-variant-branch emitters (the positional is form-level — a variant
 *  overlays keys, never children). */
function writeChildren(form: ModelForm, indent: string, ctx: EmitContext): string {
  switch (form.positional.kind) {
    case 'none':
      return '';
    case 'any':
      return `${indent}$children?: unknown[];\n`;
    case 'kind':
      return (
        childCountsDoc(form.positional.shape, indent) +
        `${indent}$children?: Array<${writeShape(form.positional.shape, ctx)}>;\n`
      );
    default:
      return assertNever(form.positional);
  }
}

/** The discriminant key inside a variant branch: narrowed to that branch's
 *  `:when` rather than the whole member set, which is what makes the union
 *  discriminate. */
function writeDiscriminantKey(key: ModelKey, when: string, indent: string): string {
  const doc = key.description ? `${indent}/** ${key.description} */\n` : '';
  return `${doc}${indent}${escapeIdentifier(key.name)}: Symbol_<"${when}">;\n`;
}

function writeFormDoc(form: ModelForm): string {
  if (!form.description && form.exclusiveGroups.length === 0) return '';
  if (form.description && form.exclusiveGroups.length === 0) {
    return `/** ${form.description} */\n`;
  }
  let out = '/**\n';
  if (form.description) {
    out += ` * ${form.description}\n`;
    if (form.exclusiveGroups.length > 0) out += ' *\n';
  }
  for (const g of form.exclusiveGroups) {
    const card = g.cardinality === 'exactly_one' ? 'exactly-one' : 'at-most-one';
    const alts = g.alternatives.map((bundle) => bundle.join(' + ')).join(', ');
    out += ` * @sjon-exclusive-group ${card} [${alts}]\n`;
  }
  out += ' */\n';
  return out;
}

function writeKey(key: ModelKey, indent: string, ctx: EmitContext): string {
  let out = '';
  const jsdoc = buildKeyJSDoc(key, indent);
  if (jsdoc) out += jsdoc;
  const optMark = key.optional ? '?' : '';
  out += `${indent}${escapeIdentifier(key.name)}${optMark}: ${writeShape(key.value, ctx)};\n`;
  return out;
}

/**
 * Emit a slot-local form as an inline anonymous object-literal type (no
 * `export interface NAME` header — locals have no global type name). Mirrors
 * `writeInlineLocalForm` in `src/SchemaExport/TsTypes.zig`: compact, single
 * line, `$ns` optional (locals are bare-invoked). A discriminated local emits
 * a parenthesised union of per-variant branches so TS narrows on the
 * discriminant brand, matching the JSON side's if/then reuse.
 */
function writeInlineLocalForm(form: ModelForm, ctx: EmitContext): string {
  const sortedKeys = [...form.keys].sort((a, b) => a.name.localeCompare(b.name));
  if (form.discriminator) {
    const disc = form.discriminator;
    const variants = disc.variants.map((v) => {
      let s = `{ $form: "${form.name}"; $ns?: string;`;
      for (const k of sortedKeys) {
        s +=
          k.name === disc.keyName
            ? ` ${escapeIdentifier(k.name)}: Symbol_<"${v.when}">;`
            : ` ${writeInlineLocalKey(k, ctx)}`;
      }
      const sortedVKeys = [...v.keys].sort((a, b) => a.name.localeCompare(b.name));
      for (const vk of sortedVKeys) s += ` ${writeInlineLocalKey(vk, ctx)}`;
      if (form.open) s += ' [key: string]: unknown;';
      s += ' }';
      return s;
    });
    return `(${variants.join(' | ')})`;
  }
  let s = `{ $form: "${form.name}"; $ns?: string;`;
  for (const k of sortedKeys) s += ` ${writeInlineLocalKey(k, ctx)}`;
  switch (form.positional.kind) {
    case 'none':
      break;
    case 'any':
      s += ' $children?: unknown[];';
      break;
    case 'kind':
      s += ` $children?: Array<${writeShape(form.positional.shape, ctx)}>;`;
      break;
    default:
      assertNever(form.positional);
  }
  if (form.open) s += ' [key: string]: unknown;';
  s += ' }';
  return s;
}

/** Compact single-line key for an inline local-form literal: `name?: T;`. */
function writeInlineLocalKey(key: ModelKey, ctx: EmitContext): string {
  const optMark = key.optional ? '?' : '';
  return `${escapeIdentifier(key.name)}${optMark}: ${writeShape(key.value, ctx)};`;
}

function buildKeyJSDoc(key: ModelKey, indent: string): string {
  const lines: string[] = [];
  if (key.description) lines.push(key.description);
  if (key.default && key.default.kind === 'expression') {
    lines.push(`@default computed via \`${key.default.snapshot.head}\``);
  }
  const bounds = numericBoundsOf(key.value);
  if (bounds) {
    if (bounds.min)
      lines.push(`@minimum ${bounds.min.value}${bounds.exclusiveMin ? ' (exclusive)' : ''}`);
    if (bounds.max)
      lines.push(`@maximum ${bounds.max.value}${bounds.exclusiveMax ? ' (exclusive)' : ''}`);
    if (bounds.integer) lines.push('@integer true');
    // TS has no divisibility constraint, so this is JSDoc-only. (Tag
    // spelling follows this host's local convention — `@integer`, not
    // Zig's `@sjon-integer` — which these JSDoc lines already use.)
    if (bounds.multipleOf) lines.push(`@multiple-of ${bounds.multipleOf.value}`);
  }
  const sb = stringBoundsOf(key.value);
  if (sb) {
    if (sb.minLen != null) lines.push(`@minLength ${sb.minLen}`);
    if (sb.maxLen != null) lines.push(`@maxLength ${sb.maxLen}`);
    if (sb.pattern) lines.push(`@pattern ${sb.pattern}`);
    if (sb.format) lines.push(`@format ${sb.format}`);
  }
  if (key.requires.length > 0) {
    // Not expressible in a plain interface — it would need a discriminated
    // union over which keys are present. Tag matches the Zig exporter's
    // byte-for-byte, since the kit-xor golden is compared directly.
    lines.push(`@sjon-requires ${key.requires.join(', ')}`);
  }
  const cr = crossRefOf(key.value);
  if (cr) {
    // Prose names only what the route can carry: `name-key` and `acyclic`
    // are identity-only (the loader rejects the first beside a provider,
    // and cycle edges need per-name declaration sites extracted names
    // don't have). Mirrors `writeCrossRefDoc` in `TsTypes.zig`.
    const route =
      cr.provider === null
        ? `name-key=${cr.nameKey} acyclic=${cr.acyclic}`
        : `provider=${cr.provider} source-key=${cr.sourceKey}`;
    lines.push(
      `@sjon-cross-ref target=${cr.targets.join(' | ')} ${route}` +
        (cr.scopeForm ? ` scope-form=${cr.scopeForm}` : ''),
    );
  }
  const rich = richMembersOf(key.value);
  if (rich) {
    for (const m of rich) {
      if (m.deprecated) lines.push(`@deprecated ${m.deprecationMessage || m.name}`);
    }
  }
  if (lines.length === 0) return '';
  // Block form whenever any line is an `@`-annotation, single-line only for
  // a lone description — mirroring `TsTypes.zig`'s `use_block` rule. The two
  // emitters are byte-compared on the `kit` / `kit-xor` goldens (modulo the
  // `:description` this port does not read), so the *shape* has to agree and
  // not just the content. Continuation lines carry `indent`, as Zig's do.
  const hasAnnotation = lines.some((l) => l.startsWith('@'));
  if (lines.length === 1 && !hasAnnotation) return `${indent}/** ${lines[0]} */\n`;
  return `${indent}/**\n` + lines.map((l) => `${indent} * ${l}`).join('\n') + `\n${indent} */\n`;
}

function writeShape(shape: ModelValueShape, ctx: EmitContext): string {
  switch (shape.kind) {
    case 'any':
      return 'unknown';
    case 'nil':
      return 'null';
    case 'boolean':
      return 'boolean';
    case 'number':
      return 'number';
    // A `:repr`-tagged number renders as its branded GPU alias
    // (`F32`…`F16`); a plain bounded number stays `number` (min/max aren't
    // expressible in a TS structural type).
    case 'number_bounded':
      return shape.bounds.repr ? reprTsAlias(shape.bounds.repr) : 'number';
    case 'number_i64':
    case 'number_u64':
      return 'bigint';
    case 'number_with_unit':
      return writeUnitTuple(shape.unit);
    case 'string':
    case 'string_with_bounds':
      return 'string';
    case 'symbol':
      return 'Symbol_';
    case 'symbol_members':
      return shape.members.map((n) => `Symbol_<"${n}">`).join(' | ');
    case 'symbol_members_rich':
      // A digit-leading member breaks the brand: a document writes `2d` as
      // a unit-bearing number, so its alternative is the `[magnitude,
      // unit]` tuple `number_with_unit` already uses. `Symbol_<"2d">` here
      // would make the `.d.ts` reject a document the validator accepts.
      return shape.members
        .map((m) =>
          m.numericSpelling !== undefined
            ? `readonly [${m.numericSpelling.magnitude}, "${m.numericSpelling.unit}"]`
            : `Symbol_<"${m.name}">`,
        )
        .join(' | ');
    case 'string_members':
    case 'string_members_rich': {
      const names =
        shape.kind === 'string_members' ? shape.members : shape.members.map((m) => m.name);
      return names.map((n) => `"${n}"`).join(' | ');
    }
    case 'date':
      return 'SjonDate';
    case 'time':
      return 'SjonTime';
    case 'keyword':
      return 'Keyword';
    case 'vector': {
      if (shape.vector.len != null && shape.vector.len <= 8) {
        return `readonly [${Array(shape.vector.len)
          .fill(writeShape(shape.vector.element, ctx))
          .join(', ')}]`;
      }
      return `Array<${writeShape(shape.vector.element, ctx)}>`;
    }
    case 'form_any':
      return '{ readonly $form: string }';
    case 'form_heads': {
      const branches = shape.heads.map((head) => {
        const ident = head.plugin
          ? formTypeName(head.plugin, head.name)
          : `{ readonly $form: "${head.name}" }`;
        return ident;
      });
      return branches.length > 0 ? branches.join(' | ') : 'never';
    }
    case 'form_locals': {
      // Inline anonymous union of object literals (one per local form), plus
      // a trailing open generic branch for the additive global fallback. TS
      // narrows on the `$form` discriminant; the open branch makes the slot
      // accept any global form (required-key enforcement on it is SJON-
      // runtime-only). Mirrors the Zig `form_locals` arm in `TsTypes.zig`.
      const branches = shape.forms.map((lf) => writeInlineLocalForm(lf, ctx));
      branches.push('{ readonly $form: string; readonly $ns?: string }');
      return branches.join(' | ');
    }
    case 'expr':
      return 'SjonExpr';
    case 'cross_ref':
      // A group is a union of brands, one per target — the honest TS
      // reading of "this name may come from either form".
      return shape.crossRef.targets.map((t) => `CrossRef<"${t}">`).join(' | ');
    case 'union_of':
      return shape.alternatives.map((a) => writeShape(a.shape, ctx)).join(' | ');
    case 'unresolved_named':
      return `unknown /* unresolved: ${shape.name} */`;
    default:
      return assertNever(shape);
  }
}

function writeUnitTuple(unit: ModelUnitShape): string {
  if (unit.allowed.length > 0) {
    return unit.allowed.map((u) => `[number, "${u}"]`).join(' | ');
  }
  return '[number, string]';
}

function writeBarrel(plugin: ModelPlugin): string {
  if (plugin.forms.length === 0) return '';
  const formNames = plugin.forms.map((f) => formTypeName(plugin.name, f.name));
  return `export type Sjon${pascalCase(plugin.name)} =\n  | ${formNames.join('\n  | ')};\n\n`;
}

// ---------------------------------------------------------------------------
// JSDoc-axis helpers
// ---------------------------------------------------------------------------

function numericBoundsOf(shape: ModelValueShape): ModelNumericBounds | null {
  if (shape.kind === 'number_bounded') return shape.bounds;
  if (shape.kind === 'number_with_unit') return shape.unit.bounds;
  return null;
}

function stringBoundsOf(shape: ModelValueShape): ModelStringBounds | null {
  if (shape.kind === 'string_with_bounds') return shape.bounds;
  return null;
}

function crossRefOf(shape: ModelValueShape): ModelCrossRef | null {
  if (shape.kind === 'cross_ref') return shape.crossRef;
  return null;
}

function richMembersOf(shape: ModelValueShape): readonly ModelMember[] | null {
  if (shape.kind === 'symbol_members_rich' || shape.kind === 'string_members_rich') {
    return shape.members;
  }
  return null;
}

// ---------------------------------------------------------------------------
// Naming
// ---------------------------------------------------------------------------

function formTypeName(plugin: string, form: string): string {
  return `${pascalCase(plugin)}_${pascalCase(form)}`;
}

function pascalCase(s: string): string {
  return s
    .split(/[-_/]/)
    .map((seg) => (seg.length === 0 ? '' : seg[0]!.toUpperCase() + seg.slice(1)))
    .join('');
}

const TS_RESERVED = new Set([
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'new',
  'null',
  'return',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
]);

function escapeIdentifier(name: string): string {
  if (TS_RESERVED.has(name)) return `"${name}"`;
  if (/[^A-Za-z0-9_$]/.test(name)) return `"${name}"`;
  return name;
}
