//! Generates one `#[test] fn` per conformance fixture under
//! `conformance/cases/`. Mirrors the discovery-time `for` loops in
//! `hosts/web/test/conformance.test.ts` and
//! `hosts/typescript-parity/test/conformance.test.ts`, so the Rust
//! host gets the same per-fixture visibility (named test, `cargo
//! test` filtering, parallel scheduling, isolation against panics).
//!
//! The runtime helpers live in `tests/conformance.rs`; this script
//! only emits dispatch stubs that call them by case name.

use std::collections::HashSet;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// Mirrors `HOST_PASS_SKIP` in `tests/conformance.rs`. Legacy cases
/// listed here are not emitted (the host pipeline emits a different
/// diagnostic set than the legacy pre-compose path).
const HOST_PASS_SKIP: &[&str] = &["too-many-keys"];

fn corpus_dir() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("../../conformance/cases");
    p
}

fn is_inline_case(case_dir: &Path) -> bool {
    case_dir.join("document.sjon").exists() && !case_dir.join("schema.sjon").exists()
}

fn is_legacy_case(case_dir: &Path) -> bool {
    case_dir.join("schema.sjon").exists()
}

fn is_lowering_case(name: &str) -> bool {
    name.starts_with("lowering-")
}

/// Lowercase + `-` → `_`. Any other non-`[a-z0-9_]` byte becomes `_`
/// too, so quirky names still produce a valid Rust identifier.
fn sanitize(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push('_');
        }
    }
    out
}

fn main() -> Result<(), Box<dyn Error>> {
    let corpus = corpus_dir();
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", corpus.display());

    let mut entries: Vec<String> = fs::read_dir(&corpus)?
        .filter_map(Result::ok)
        .filter(|d| d.file_type().ok().is_some_and(|t| t.is_dir()))
        .map(|d| d.file_name().to_string_lossy().into_owned())
        .collect();
    entries.sort();

    let mut emitted: HashSet<String> = HashSet::new();
    let mut body = String::new();
    body.push_str("// @generated by build.rs from conformance/cases — do not edit.\n\n");

    let mut inline_count = 0usize;
    let mut legacy_count = 0usize;
    for name in &entries {
        let case_dir = corpus.join(name);
        let (prefix, helper) = if is_inline_case(&case_dir) {
            if is_lowering_case(name) {
                continue;
            }
            inline_count += 1;
            ("inline", "run_inline_case")
        } else if is_legacy_case(&case_dir) {
            if HOST_PASS_SKIP.contains(&name.as_str()) {
                continue;
            }
            legacy_count += 1;
            ("legacy", "run_legacy_case_as_host")
        } else {
            continue;
        };

        let fn_name = format!("{prefix}_{}", sanitize(name));
        if !emitted.insert(fn_name.clone()) {
            return Err(format!(
                "conformance build.rs: sanitized test name `{fn_name}` collides — fixture `{name}` would shadow an earlier case"
            )
            .into());
        }
        writeln!(body, "#[test]\nfn {fn_name}() {{ {helper}(\"{name}\"); }}")?;
    }

    if inline_count == 0 || legacy_count == 0 {
        return Err(format!(
            "conformance build.rs: expected both inline and legacy fixtures (inline={inline_count}, legacy={legacy_count}) under {}",
            corpus.display()
        )
        .into());
    }

    let out_dir = std::env::var_os("OUT_DIR").ok_or("OUT_DIR not set")?;
    let out_path = PathBuf::from(out_dir).join("conformance_generated.rs");
    fs::write(&out_path, body)?;
    Ok(())
}
