//! `sjon completions SHELL` renderers — bash / zsh / fish scripts.
//!
//! Split out of `Cli.zig` to keep the dispatcher readable. Pure output:
//! each renderer takes the CLI's command `Vocabulary` (verbs,
//! subcommands, flags — owned by `Cli.zig`, the single source of truth)
//! and writes a self-contained completion script to `out`. Nothing here
//! reaches back into `Cli` (std-only), so the dependency is one-way.
//!
//! `Cli_tests.zig` asserts every vocabulary entry round-trips through
//! `parseArgs` AND appears in each generated script, so a renderer can't
//! advertise a verb the dispatcher doesn't accept, or drop one it does.

const std = @import("std");
const Writer = std.Io.Writer;

/// The CLI's command surface, passed in by the dispatcher. Slices, not
/// arrays, so the renderers stay agnostic to how `Cli` stores them.
pub const Vocabulary = struct {
    top_level_verbs: []const []const u8,
    plugin_subcommands: []const []const u8,
    project_subcommands: []const []const u8,
    common_flags: []const []const u8,
};

/// Write `words` space-separated, no surrounding whitespace — the body
/// of a `bash`/`zsh` candidate list or a fish `-a '…'` argument set.
fn writeWordList(out: *Writer, words: []const []const u8) Writer.Error!void {
    for (words, 0..) |w, i| {
        if (i != 0) try out.writeByte(' ');
        try out.writeAll(w);
    }
}

/// Strip a flag token down to its bare name: drop the leading dashes and
/// a trailing `=`. `--project-root=` → `project-root`. Used by the fish
/// renderer (`complete … -l <name>`) and mirrored by the drift guard.
fn flagBareName(flag: []const u8) []const u8 {
    var s = flag;
    while (std.mem.startsWith(u8, s, "-")) s = s[1..];
    if (std.mem.endsWith(u8, s, "=")) s = s[0 .. s.len - 1];
    return s;
}

pub fn writeBash(out: *Writer, vocab: Vocabulary) Writer.Error!void {
    try out.writeAll(
        \\# sjon bash completion.
        \\# Generated by `sjon completions bash`. Source it, or install into
        \\# your bash-completion.d directory:
        \\#   sjon completions bash > /usr/local/etc/bash_completion.d/sjon
        \\_sjon() {
        \\    local cur="${COMP_WORDS[COMP_CWORD]}"
        \\    local verbs="
    );
    try writeWordList(out, vocab.top_level_verbs);
    try out.writeAll(
        \\"
        \\    local plugin_subs="
    );
    try writeWordList(out, vocab.plugin_subcommands);
    try out.writeAll(
        \\"
        \\    local project_subs="
    );
    try writeWordList(out, vocab.project_subcommands);
    try out.writeAll(
        \\"
        \\    local flags="
    );
    try writeWordList(out, vocab.common_flags);
    try out.writeAll(
        \\"
        \\
        \\    if [ "$COMP_CWORD" -eq 1 ]; then
        \\        COMPREPLY=( $(compgen -W "$verbs" -- "$cur") )
        \\        return
        \\    fi
        \\
        \\    case "${COMP_WORDS[1]}" in
        \\        plugin)
        \\            if [ "$COMP_CWORD" -eq 2 ]; then
        \\                COMPREPLY=( $(compgen -W "$plugin_subs" -- "$cur") )
        \\                return
        \\            fi
        \\            ;;
        \\        project)
        \\            if [ "$COMP_CWORD" -eq 2 ]; then
        \\                COMPREPLY=( $(compgen -W "$project_subs" -- "$cur") )
        \\                return
        \\            fi
        \\            ;;
        \\    esac
        \\
        \\    if [[ "$cur" == -* ]]; then
        \\        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
        \\        return
        \\    fi
        \\
        \\    COMPREPLY=( $(compgen -f -- "$cur") )
        \\}
        \\complete -F _sjon sjon
        \\
    );
}

pub fn writeZsh(out: *Writer, vocab: Vocabulary) Writer.Error!void {
    try out.writeAll(
        \\#compdef sjon
        \\# sjon zsh completion. Generated by `sjon completions zsh`. Install
        \\# onto your $fpath as `_sjon`, e.g.:
        \\#   sjon completions zsh > "${fpath[1]}/_sjon"
        \\_sjon() {
        \\    local -a verbs plugin_subs project_subs flags
        \\    verbs=(
    );
    try writeWordList(out, vocab.top_level_verbs);
    try out.writeAll(
        \\)
        \\    plugin_subs=(
    );
    try writeWordList(out, vocab.plugin_subcommands);
    try out.writeAll(
        \\)
        \\    project_subs=(
    );
    try writeWordList(out, vocab.project_subcommands);
    try out.writeAll(
        \\)
        \\    flags=(
    );
    try writeWordList(out, vocab.common_flags);
    try out.writeAll(
        \\)
        \\
        \\    if (( CURRENT == 2 )); then
        \\        _describe -t commands 'sjon command' verbs
        \\        return
        \\    fi
        \\
        \\    case "${words[2]}" in
        \\        plugin)
        \\            if (( CURRENT == 3 )); then
        \\                _describe -t commands 'plugin subcommand' plugin_subs
        \\                return
        \\            fi
        \\            ;;
        \\        project)
        \\            if (( CURRENT == 3 )); then
        \\                _describe -t commands 'project subcommand' project_subs
        \\                return
        \\            fi
        \\            ;;
        \\    esac
        \\
        \\    _describe -t options 'option' flags
        \\    _files
        \\}
        \\
        \\_sjon "$@"
        \\
    );
}

pub fn writeFish(out: *Writer, vocab: Vocabulary) Writer.Error!void {
    try out.writeAll(
        \\# sjon fish completion. Generated by `sjon completions fish`. Install
        \\# to ~/.config/fish/completions/sjon.fish:
        \\#   sjon completions fish > ~/.config/fish/completions/sjon.fish
        \\
        \\# Top-level verbs (offered only before a subcommand is given).
        \\complete -c sjon -f -n '__fish_use_subcommand' -a '
    );
    try writeWordList(out, vocab.top_level_verbs);
    try out.writeAll(
        \\'
        \\
        \\# `plugin` subcommands.
        \\complete -c sjon -f -n '__fish_seen_subcommand_from plugin' -a '
    );
    try writeWordList(out, vocab.plugin_subcommands);
    try out.writeAll(
        \\'
        \\
        \\# `project` subcommands.
        \\complete -c sjon -f -n '__fish_seen_subcommand_from project' -a '
    );
    try writeWordList(out, vocab.project_subcommands);
    try out.writeAll(
        \\'
        \\
        \\# Flags. Value-taking flags are marked `-r` (require an argument).
        \\
    );
    for (vocab.common_flags) |flag| {
        const bare = flagBareName(flag);
        const takes_value = std.mem.endsWith(u8, flag, "=");
        try out.print("complete -c sjon -l {s}{s}\n", .{ bare, if (takes_value) " -r" else "" });
    }
}
