// sjon-export-version: 1
// Generated by sjon — do not edit by hand.
// Describes the canonical JSON shape of `sjon to-json`.
//
// Export warnings:
//   [info string_bounds_emitted_via_keywords] value-kind `slug` — string bounds emitted via `minLength`/`maxLength`/`pattern`/`format`
//   [info string_bounds_emitted_via_keywords] value-kind `email` — string bounds emitted via `minLength`/`maxLength`/`pattern`/`format`
//   [info numeric_bounds_emitted_via_min_max] value-kind `num-min0-max100` — numeric bounds emitted via `minimum`/`maximum`
//   [warn cross_ref_unenforceable] value-kind `ref-account` cross-ref: schema validates symbol shape only; closed-set membership requires SJON-aware validator
//   [info cross_ref_annotation_only] value-kind `ref-account` cross-ref annotation surfaces target-form=`account` name-key=`name` acyclic=false scope-form=``; none are enforceable by JSON Schema
//   [warn expression_slot_annotation_only] expression slot — runtime type unverifiable by JSON Schema

export type Keyword<S extends string = string> = { readonly $kw: S };
export type Symbol_<S extends string = string> = { readonly $sym: S };
export type SjonDate = { readonly $date: string };
export type SjonTime = { readonly $time: string };
export type SjonExpr<TResult = unknown> = { readonly $expr: unknown[] } & { readonly __sjonResult?: TResult };
export type CrossRef<TargetForm extends string = string, S extends string = string> = Symbol_<S> & { readonly __sjonRef?: TargetForm };
export type F32 = number & { readonly __sjonRepr?: "f32" };
export type U32 = number & { readonly __sjonRepr?: "u32" };
export type I32 = number & { readonly __sjonRepr?: "i32" };
export type U16 = number & { readonly __sjonRepr?: "u16" };
export type F16 = number & { readonly __sjonRepr?: "f16" };


// ----- plugin: bounds -----

export interface Bounds_Profile {
  $form: "profile";
  $ns: "bounds";
  active: boolean;
  age: number;
  bio?: string;
  coord: readonly [number, number, number];
  /** @format email */
  email: string;
  formula: SjonExpr;
  /** @pattern ^[a-z][a-z0-9-]*$ */
  handle: string;
  meta?: { readonly $form: string };
  notes: Array<unknown>;
  /** @sjon-cross-ref target=account name-key=name acyclic=false */
  owner: CrossRef<"account">;
  role: Symbol_<"admin"> | Symbol_<"user">;
  /**
 * @minimum 0
 * @maximum 100
 */
  score?: number;
  status: "active" | "archived";
  tags: Array<string>;
}

export type SjonBounds =
  | Bounds_Profile;

