const std = @import("std");
const Ast = @import("Ast.zig");
const Parser = @import("Parser.zig");

const Allocator = std.mem.Allocator;
const Io = std.Io;
const Sha256 = std.crypto.hash.sha2.Sha256;

pub const FORMAT_VERSION: u32 = 1;

pub const Error = error{ OutOfMemory, Corrupt, UnsupportedVersion };

pub const ResolvedFrom = enum { project_plugins, search_roots };

pub const LockedEntry = struct {
    name: []const u8,
    version: []const u8,
    path: []const u8,
    manifest_hash: []const u8,
    wasm_hash: ?[]const u8 = null,
    resolved_from: ResolvedFrom = .project_plugins,
};

pub const Lockfile = struct {
    arena: std.heap.ArenaAllocator,
    version: u32 = FORMAT_VERSION,
    project_hash: ?[]const u8 = null,
    generated_at: ?[]const u8 = null,
    sjon_version: ?[]const u8 = null,
    plugins: []const LockedEntry = &.{},

    pub fn deinit(self: *Lockfile) void {
        self.arena.deinit();
    }

    pub fn find(self: *const Lockfile, name: []const u8) ?*const LockedEntry {
        for (self.plugins) |*p| {
            if (std.mem.eql(u8, p.name, name)) return p;
        }
        return null;
    }
};

pub fn hashBytes(arena: Allocator, bytes: []const u8) Allocator.Error![]const u8 {
    var digest: [Sha256.digest_length]u8 = undefined;
    Sha256.hash(bytes, &digest, .{});
    const hex = std.fmt.bytesToHex(digest, .lower);
    return try std.fmt.allocPrint(arena, "sha256-{s}", .{hex});
}

pub fn write(
    arena: Allocator,
    lf: Lockfile,
) Allocator.Error![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    try buf.appendSlice(arena, "; sjon-project.lock — DO NOT EDIT BY HAND.\n");
    try buf.appendSlice(arena, "; Generated by `sjon project lock`. Verify with `sjon project verify`.\n");
    try buf.appendSlice(arena, "\n");
    try buf.appendSlice(arena, "(lockfile :version ");
    const ver_str = try std.fmt.allocPrint(arena, "{d}", .{lf.version});
    try buf.appendSlice(arena, ver_str);
    try buf.appendSlice(arena, "\n");
    if (lf.project_hash) |h| {
        try buf.appendSlice(arena, "          :project-hash \"");
        try buf.appendSlice(arena, h);
        try buf.appendSlice(arena, "\"\n");
    }
    if (lf.generated_at) |t| {
        try buf.appendSlice(arena, "          :generated-at \"");
        try buf.appendSlice(arena, t);
        try buf.appendSlice(arena, "\"\n");
    }
    if (lf.sjon_version) |v| {
        try buf.appendSlice(arena, "          :sjon-version \"");
        try buf.appendSlice(arena, v);
        try buf.appendSlice(arena, "\"\n");
    }
    try buf.appendSlice(arena, "          :plugins\n");
    try buf.appendSlice(arena, "          [");
    for (lf.plugins, 0..) |entry, idx| {
        if (idx > 0) try buf.appendSlice(arena, "\n           ");
        try buf.appendSlice(arena, "(locked :name          ");
        try buf.appendSlice(arena, entry.name);
        try buf.appendSlice(arena, "\n                   :version       \"");
        try buf.appendSlice(arena, entry.version);
        try buf.appendSlice(arena, "\"\n                   :path          \"");
        try buf.appendSlice(arena, entry.path);
        try buf.appendSlice(arena, "\"\n                   :manifest-hash \"");
        try buf.appendSlice(arena, entry.manifest_hash);
        try buf.appendSlice(arena, "\"");
        if (entry.wasm_hash) |wh| {
            try buf.appendSlice(arena, "\n                   :wasm-hash     \"");
            try buf.appendSlice(arena, wh);
            try buf.appendSlice(arena, "\"");
        }
        try buf.appendSlice(arena, "\n                   :resolved-from ");
        try buf.appendSlice(arena, switch (entry.resolved_from) {
            .project_plugins => "project-plugins",
            .search_roots => "search-roots",
        });
        try buf.appendSlice(arena, ")");
    }
    try buf.appendSlice(arena, "])\n");
    return try buf.toOwnedSlice(arena);
}

pub fn parse(gpa: Allocator, source: [:0]const u8) Error!Lockfile {
    var arena = std.heap.ArenaAllocator.init(gpa);
    errdefer arena.deinit();
    const a = arena.allocator();

    var tree = try Parser.parse(gpa, source);
    defer tree.deinit();
    if (tree.root.len != 1) return error.Corrupt;
    const root = tree.root[0];
    if (tree.tagOf(root) != .form) return error.Corrupt;
    const hdr = tree.formHeader(root);
    if (!std.mem.eql(u8, hdr.head, "lockfile")) return error.Corrupt;

    var version: u32 = FORMAT_VERSION;
    var project_hash: ?[]const u8 = null;
    var generated_at: ?[]const u8 = null;
    var sjon_version: ?[]const u8 = null;
    var plugins: std.ArrayList(LockedEntry) = .empty;

    for (hdr.children) |ci| {
        if (tree.tagOf(ci) != .kvpair) continue;
        const kv = tree.kvpairHeader(ci);
        if (std.mem.eql(u8, kv.key, "version")) {
            if (tree.tagOf(kv.value) != .number_i64) return error.Corrupt;
            const v: i64 = tree.numberI64Of(kv.value);
            if (v < 0) return error.Corrupt;
            version = @intCast(v);
            if (version > FORMAT_VERSION) return error.UnsupportedVersion;
        } else if (std.mem.eql(u8, kv.key, "project-hash") and tree.tagOf(kv.value) == .string) {
            project_hash = try a.dupe(u8, tree.stringText(kv.value));
        } else if (std.mem.eql(u8, kv.key, "generated-at") and tree.tagOf(kv.value) == .string) {
            generated_at = try a.dupe(u8, tree.stringText(kv.value));
        } else if (std.mem.eql(u8, kv.key, "sjon-version") and tree.tagOf(kv.value) == .string) {
            sjon_version = try a.dupe(u8, tree.stringText(kv.value));
        } else if (std.mem.eql(u8, kv.key, "plugins")) {
            if (tree.tagOf(kv.value) != .vector) return error.Corrupt;
            for (tree.vectorElements(kv.value)) |elem| {
                try plugins.append(a, try parseLocked(a, tree, elem));
            }
        }
    }
    const owned_plugins = try plugins.toOwnedSlice(a);
    return Lockfile{
        .arena = arena,
        .version = version,
        .project_hash = project_hash,
        .generated_at = generated_at,
        .sjon_version = sjon_version,
        .plugins = owned_plugins,
    };
}

fn parseLocked(a: Allocator, tree: Ast.Tree, idx: Ast.NodeIndex) Error!LockedEntry {
    if (tree.tagOf(idx) != .form) return error.Corrupt;
    const hdr = tree.formHeader(idx);
    if (!std.mem.eql(u8, hdr.head, "locked")) return error.Corrupt;

    var entry: LockedEntry = .{
        .name = "",
        .version = "",
        .path = "",
        .manifest_hash = "",
    };
    for (hdr.children) |ci| {
        if (tree.tagOf(ci) != .kvpair) continue;
        const kv = tree.kvpairHeader(ci);
        if (std.mem.eql(u8, kv.key, "name") and tree.tagOf(kv.value) == .symbol) {
            entry.name = try a.dupe(u8, tree.symbolText(kv.value));
        } else if (std.mem.eql(u8, kv.key, "version") and tree.tagOf(kv.value) == .string) {
            entry.version = try a.dupe(u8, tree.stringText(kv.value));
        } else if (std.mem.eql(u8, kv.key, "path") and tree.tagOf(kv.value) == .string) {
            entry.path = try a.dupe(u8, tree.stringText(kv.value));
        } else if (std.mem.eql(u8, kv.key, "manifest-hash") and tree.tagOf(kv.value) == .string) {
            entry.manifest_hash = try a.dupe(u8, tree.stringText(kv.value));
        } else if (std.mem.eql(u8, kv.key, "wasm-hash") and tree.tagOf(kv.value) == .string) {
            entry.wasm_hash = try a.dupe(u8, tree.stringText(kv.value));
        } else if (std.mem.eql(u8, kv.key, "resolved-from") and tree.tagOf(kv.value) == .symbol) {
            const sym = tree.symbolText(kv.value);
            entry.resolved_from = if (std.mem.eql(u8, sym, "search-roots"))
                .search_roots
            else
                .project_plugins;
        }
    }
    if (entry.name.len == 0 or entry.manifest_hash.len == 0) return error.Corrupt;
    return entry;
}

pub fn sortEntries(entries: []LockedEntry) void {
    std.mem.sort(LockedEntry, entries, {}, lessThan);
}

fn lessThan(_: void, a: LockedEntry, b: LockedEntry) bool {
    return std.mem.lessThan(u8, a.name, b.name);
}

const testing = std.testing;
